#Deployment do Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: "kube#123"
          - name: POSTGRES_USER
            value: "kubenews"
          - name : POSTGRES_DB
            value: "kubenews"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels: 
        app: kubenews
    spec:
      containers:
        - name: kubenews
          image: dhelly/kube-news:v1
          env: 
          - name: DB_DATABASE
            value: "kubenews"
          - name: DB_USERNAME
            value: "kubenews"
          - name: DB_PASSWORD
            value: "kube#123"
          - name: DB_HOST
            value: "postgres"

---

apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - protocol: TCP
    port: 80
    targerPort: 8080
    nodePort: 30000
  type: NodePort
